version: "3.8"

#los servicios son los multiples contenedores que puedo crear (mysql, redis, nginx, apache2)
services:
  mysqldb:
    #Le estoy diciendo que este servicio está basado en mysql
    image: mysql:5.7
    # restart: unless-stopped
    env_file: ./.env
    # las variables de entorno
    environment:
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE

    #internamente mysql trabaja en el puerto 3306
    #puedo utilizar 3307:3306 el puerto interno 3306 es el que utiliza mysql, y el 3307 es el puerto que quiero yo conectarme
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    logging:
      driver: none

  app:
    depends_on:
      - mysqldb
    links:
      - mysqldb
    build: .
    # restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=$MYSQLDB_HOST
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    volumes:
      - .:/myapp
    command: sh -c "npm install && npm run dev"

